import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Navbar from '../components/navbar';
import { Button } from '@mui/material';
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home | Cesi'Eats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/UberEats-LogoPNG1.png" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main className={styles.main}>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
